go:
    version: 1.18
repository:
    path: github.com/stakefish/cosmos-watcher
build:
    binaries:
        - name: bin/cosmos-watcher
          path: ./cmd/cosmos-watcher
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
